apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: process-migration
spec:
  environment: rhpam-trial
  objects:
    processMigration:
      image: "rhpam-process-migration-rhel8-mssql"
      database:
        type: external
        externalConfig:
          driver: mariadb
          jdbcURL: jdbc:mariadb://[[.ApplicationName]]-process-migration-mysql:3306/pimdb?useUnicode=true&useSSL=false&serverTimezone=UTC
          username: pim
          password: pim
          minPoolSize: "10"
          maxPoolSize: "10"
          connectionChecker: org.jboss.jca.adapters.jdbc.extensions.mysql.MySQLValidConnectionChecker
          exceptionSorter: org.jboss.jca.adapters.jdbc.extensions.mysql.MySQLExceptionSorter
          backgroundValidation: "false"
          backgroundValidationMillis: "150000"
