apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: process-migration
spec:
  environment: rhpam-trial
  objects:
    processMigration:
      image: "rhpam-process-migration-rhel8"
      database:
        type: "postgresql"
