## KIE ProcessMigration BEGIN
processMigration:
  ## KIE ProcessMigration deployment config BEGIN
  deploymentConfigs:
    - metadata:
        name: "[[.ApplicationName]]-process-migration"
      spec:
        template:
          spec:
            initContainers:
              - command:
                  [
                    "/bin/bash",
                    "-c",
                    ">-
                    replicas=$(oc get dc [[.ApplicationName]]-process-migration-postgresql -o=jsonpath='{.status.availableReplicas}'); until '[' $replicas -gt 0 ']'; do echo waiting for [[.ApplicationName]]-process-migration-postgresql; replicas=$(oc get dc [[.ApplicationName]]-process-migration-postgresql -o=jsonpath='{.status.availableReplicas}'); sleep 2; done;",
                  ]
                image: "[[$.Constants.OseCliImageURL]]"
                imagePullPolicy: IfNotPresent
                name: "[[.ApplicationName]]-process-migration-postgresql-init"
                terminationMessagePolicy: FallbackToLogsOnError
            containers:
              - name: "[[.ApplicationName]]-process-migration"
                env:
                  - name: JBOSS_KIE_EXTRA_CLASSPATH
                    value: "/opt/rhpam-process-migration/drivers/postgresql-jdbc.jar"
  ## KIE ProcessMigration deployment config END
  ## PostgreSQL deployment config BEGIN
    - metadata:
        name: "[[.ApplicationName]]-process-migration-postgresql"
        labels:
          app: "[[$.ApplicationName]]"
          application: "[[$.ApplicationName]]"
          service: "[[.ApplicationName]]-process-migration-postgresql"
      spec:
        strategy:
          rollingParams:
            maxSurge: 100%
            maxUnavailable: 0
          type: Rolling
        triggers:
          - type: ConfigChange
        replicas: 1
        selector:
          deploymentConfig: "[[.ApplicationName]]-process-migration-postgresql"
        template:
          metadata:
            name: "[[.ApplicationName]]-process-migration-postgresql"
            labels:
              deploymentConfig: "[[.ApplicationName]]-process-migration-postgresql"
              app: "[[$.ApplicationName]]"
              application: "[[$.ApplicationName]]"
              service: "[[.ApplicationName]]-process-migration-postgresql"
          spec:
            containers:
              - name: "[[.ApplicationName]]-process-migration-postgresql"
                image: "[[$.Constants.PostgreSQLImageURL]]"
                imagePullPolicy: IfNotPresent
                livenessProbe:
                  exec:
                    command:
                      - "/usr/libexec/check-container"
                      - "--live"
                  initialDelaySeconds: 120
                  timeoutSeconds: 10
                readinessProbe:
                  exec:
                    command:
                      - "/usr/libexec/check-container"
                  initialDelaySeconds: 5
                  timeoutSeconds: 1
                ports:
                  - containerPort: 5432
                    protocol: TCP
                env:
                  - name: POSTGRESQL_USER
                    value: "pim"
                  - name: POSTGRESQL_PASSWORD
                    value: "[[$.DBPassword]]"
                  - name: POSTGRESQL_DATABASE
                    value: "pimdb"
                  - name: POSTGRESQL_MAX_PREPARED_TRANSACTIONS
                    value: "100"
                volumeMounts:
                  - mountPath: "/var/lib/pgsql/data"
                    name: "[[.ApplicationName]]-process-migration-postgresql-[[$.Constants.DatabaseVolumeSuffix]]"
            ##[[ if ne .ProcessMigration.Database.Size "" ]]
            volumes:
              - name: "[[.ApplicationName]]-process-migration-postgresql-[[$.Constants.DatabaseVolumeSuffix]]"
                persistentVolumeClaim:
                  claimName: "[[.ApplicationName]]-process-migration-postgresql-claim"
  ## PostgreSQL deployment config END
  ## PostgreSQL persistent volume claim BEGIN
  persistentVolumeClaims:
    - metadata:
        name: "[[.ApplicationName]]-process-migration-postgresql-claim"
        labels:
          app: "[[$.ApplicationName]]"
          application: "[[$.ApplicationName]]"
          service: "[[.ApplicationName]]-process-migration-postgresql"
      spec:
        # [[ if ne .ProcessMigration.Database.StorageClassName "" ]]
        storageClassName: "[[.ProcessMigration.Database.StorageClassName]]"
        # [[ end ]]
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "[[.ProcessMigration.Database.Size]]"
            ## PostgreSQL persistent volume claim END
            ##[[ else ]]
            volumes:
              - name: "[[.ApplicationName]]-process-migration-postgresql-[[$.Constants.DatabaseVolumeSuffix]]"
                emptyDir: {}
  ##[[ end ]]
  ## PostgreSQL persistent volume claim END
  ## PostgreSQL service BEGIN
  services:
    - metadata:
        annotations:
          description: The database server's port.
        labels:
          application: prod
          service: "[[.ApplicationName]]-process-migration-postgresql"
        name: "[[.ApplicationName]]-process-migration-postgresql"
      spec:
        ports:
          - port: 5432
            targetPort: 5432
        selector:
          deploymentConfig: "[[.ApplicationName]]-process-migration-postgresql"
  ## PostgreSQL service END
  ## KIE ProcessMigration ConfigMap BEGIN
  configMaps:
    - metadata:
        name: "[[.ApplicationName]]-process-migration"
      data:
        project-overrides.yml: |-
          kieservers:
            #[[range $index, $Map := .ProcessMigration.KieServerClients]]
            - host: [[.Host]]
              username: [[.Username]]
              password: [[.Password]]
            #[[end]]
          thorntail:
            datasources:
              data-sources:
                pimDS:
                  driver-name: postgresql
                  connection-url: jdbc:postgresql://[[.ApplicationName]]-process-migration-postgresql:5432/pimdb
                  user-name: pim
                  password: "[[$.DBPassword]]"
  ## KIE ProcessMigration ConfigMap END
## KIE ProcessMigration END
